{
 "title": "Samarth's Sensor Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "heat_index",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "temperature",
     "query": "SELECT LAST(\"value\") FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "temperature",
     "query": "SELECT LAST(\"value\") FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Temperature comparison",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Indoor",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Outdoor",
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "heat_index",
     "query": "SELECT \"value\" FROM \"heat_index\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "humidity",
     "query": "SELECT LAST(\"value\") FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "humidity",
     "query": "SELECT LAST(\"value\") FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Humidity comparison",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity", "label": "Relative Humidity" }
   ],
   "targets": [
    {
     "alias": "Indoor",
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Outdoor",
     "measurement": "humidity",
     "query": "SELECT \"value\" FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Indoor",
     "measurement": "dew_point",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Outdoor",
     "measurement": "dew_point",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "aqi",
     "query": "SELECT LAST(\"value\") FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "aqi",
     "query": "SELECT LAST(\"value\") FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "AQI comparison",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "AQI" }
   ],
   "targets": [
    {
     "alias": "Indoor",
     "measurement": "aqi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Outdoor",
     "measurement": "aqi",
     "query": "SELECT \"value\" FROM \"humidity\" WHERE (\"location\" = 'outdoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Vapour Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Indoor",
     "measurement": "vapour_pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Outdoor",
     "measurement": "vapour_pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  }
 ]
}